exports.components = [
    "asset",
    "event-dispatcher",
    "expression-language",
    "filesystem",
    "form",
    "http-client",
    "http-foundation",
    "intl",
    "mailer",
    "mercure",
    "messenger",
    "process",
    "orm-pack",
    "security",
    "serializer-pack",
    "stopwatch",
    "string",
    "translation",
    "twig-pack",
    "validator",
    "web-link",
    "webpack-encore",
    "workflow",
];

exports.devComponents = [
    "debug-pack",
    "phpunit-bridge",
    "profiler-pack",
    "test-pack",
];
